/* ============================================
   LumiStrip — Template Presets
   15 distinct Korean-photo-booth-inspired strip
   designs. No two share a look.
   ============================================ */

import type { Template } from '../types';

export const TEMPLATES: Template[] = [
  {
    id: 'korean-minimal-white',
    name: 'Korean Minimal White',
    category: 'minimal',
    description: 'Crisp white space, thin ink border, nothing extra',
    colors: { primary: '#221D28', secondary: '#4A4152', accent: '#F0B94E', background: '#FFFFFF' },
    stripStyle: {
      borderRadius: 6, padding: 14, gap: 6,
      backgroundColor: '#FFFFFF', borderColor: '#221D28', borderWidth: 1,
      shadowColor: 'rgba(34,29,40,0.08)', texture: 'none',
    },
    fonts: { display: 'Noto Sans KR', body: 'Inter' },
    decorations: { showDateStamp: true, showCaption: false, showBorder: true, showFilmBorder: false, showVignette: false },
    isPremium: false,
  },
  {
    id: 'dreamy-lavender',
    name: 'Dreamy Lavender',
    category: 'premium',
    description: 'Soft dusty lilac with a hazy, floating feeling',
    colors: { primary: '#6E63A6', secondary: '#C9BFE8', accent: '#F4C7C3', background: '#F1EDFB' },
    stripStyle: {
      borderRadius: 22, padding: 18, gap: 8,
      backgroundColor: '#F1EDFB', shadowColor: 'rgba(110,99,166,0.22)', texture: 'paper',
    },
    fonts: { display: 'Fraunces', body: 'Inter' },
    decorations: { showDateStamp: true, showCaption: true, showBorder: false, showFilmBorder: false, showVignette: true },
    isPremium: true,
  },
  {
    id: 'pink-ribbon',
    name: 'Pink Ribbon',
    category: 'classic',
    description: 'A flash-pink strip wrapped like a little gift',
    colors: { primary: '#C4595A', secondary: '#E8A6A3', accent: '#F4C7C3', background: '#FFF6F5' },
    stripStyle: {
      borderRadius: 16, padding: 16, gap: 8,
      backgroundColor: '#FFF6F5', borderColor: '#F4C7C3', borderWidth: 2,
      shadowColor: 'rgba(232,166,163,0.3)', texture: 'none',
    },
    fonts: { display: 'Gaegu', body: 'Inter' },
    decorations: { showDateStamp: true, showCaption: true, showBorder: true, showFilmBorder: false, showVignette: false },
    isPremium: false,
  },
  {
    id: 'night-sky',
    name: 'Night Sky',
    category: 'premium',
    description: 'Deep plum-black with a starlit, cinematic hush',
    colors: { primary: '#F0B94E', secondary: '#C9BFE8', accent: '#F0B94E', background: '#17151C' },
    stripStyle: {
      borderRadius: 18, padding: 16, gap: 8,
      backgroundColor: '#17151C', shadowColor: 'rgba(240,185,78,0.25)', texture: 'none',
    },
    fonts: { display: 'Playfair Display', body: 'Inter' },
    decorations: { showDateStamp: true, showCaption: true, showBorder: false, showFilmBorder: false, showVignette: true },
    isPremium: true,
  },
  {
    id: 'sakura-blossom',
    name: 'Sakura Blossom',
    category: 'vintage',
    description: 'Petal-pink paper with a hand-lettered caption',
    colors: { primary: '#C4595A', secondary: '#F4C7C3', accent: '#A9C2A0', background: '#FFF9F5' },
    stripStyle: {
      borderRadius: 14, padding: 16, gap: 8,
      backgroundColor: '#FFF9F5', shadowColor: 'rgba(196,89,90,0.15)', texture: 'paper',
    },
    fonts: { display: 'Nanum Pen Script', body: 'Inter' },
    decorations: { showDateStamp: false, showCaption: true, showBorder: false, showFilmBorder: false, showVignette: false },
    isPremium: false,
  },
  {
    id: 'film-camera',
    name: 'Film Camera',
    category: 'retro',
    description: 'Real 35mm sprocket holes and a grainy finish',
    colors: { primary: '#221D28', secondary: '#4A4152', accent: '#F0B94E', background: '#F3EFE7' },
    stripStyle: {
      borderRadius: 4, padding: 20, gap: 10,
      backgroundColor: '#F3EFE7', borderColor: '#221D28', borderWidth: 3,
      shadowColor: 'rgba(0,0,0,0.25)', texture: 'vintage',
    },
    fonts: { display: 'Space Mono', body: 'Space Mono' },
    decorations: { showDateStamp: true, showCaption: false, showBorder: true, showFilmBorder: true, showVignette: true },
    isPremium: false,
  },
  {
    id: 'y2k-chrome',
    name: 'Y2K Chrome',
    category: 'modern',
    description: 'Brushed silver gradient with a pop of electric pink',
    colors: { primary: '#8891A0', secondary: '#E8A6A3', accent: '#C9BFE8', background: '#E4E7EC' },
    stripStyle: {
      borderRadius: 24, padding: 14, gap: 6,
      backgroundColor: 'linear-gradient(160deg, #F4F6F8 0%, #C7CDD6 45%, #F4F6F8 100%)',
      shadowColor: 'rgba(136,145,160,0.35)', texture: 'none',
    },
    fonts: { display: 'Space Mono', body: 'Inter' },
    decorations: { showDateStamp: true, showCaption: false, showBorder: false, showFilmBorder: false, showVignette: false },
    isPremium: true,
  },
  {
    id: 'pastel-hearts',
    name: 'Pastel Hearts',
    category: 'classic',
    description: 'Playful pastel blocks, made for sticker overload',
    colors: { primary: '#C4595A', secondary: '#C9BFE8', accent: '#F0B94E', background: '#FDF2F8' },
    stripStyle: {
      borderRadius: 20, padding: 16, gap: 10,
      backgroundColor: '#FDF2F8', shadowColor: 'rgba(196,89,90,0.18)', texture: 'none',
    },
    fonts: { display: 'Jua', body: 'Inter' },
    decorations: { showDateStamp: false, showCaption: true, showBorder: false, showFilmBorder: false, showVignette: false },
    isPremium: false,
  },
  {
    id: 'cafe-diary',
    name: 'Cafe Diary',
    category: 'vintage',
    description: 'Warm latte tones like a scrapbook page',
    colors: { primary: '#6B4A34', secondary: '#A9764F', accent: '#A9C2A0', background: '#F3E7D8' },
    stripStyle: {
      borderRadius: 8, padding: 18, gap: 10,
      backgroundColor: '#F3E7D8', borderColor: '#A9764F', borderWidth: 1,
      shadowColor: 'rgba(107,74,52,0.2)', texture: 'paper',
    },
    fonts: { display: 'Crimson Text', body: 'Crimson Text' },
    decorations: { showDateStamp: true, showCaption: true, showBorder: true, showFilmBorder: false, showVignette: false },
    isPremium: false,
  },
  {
    id: 'vintage-film',
    name: 'Vintage Film',
    category: 'vintage',
    description: 'Sepia tones, soft grain, an old roll of film',
    colors: { primary: '#8A6D3B', secondary: '#C9A66B', accent: '#F0B94E', background: '#EFE3CC' },
    stripStyle: {
      borderRadius: 6, padding: 16, gap: 8,
      backgroundColor: '#EFE3CC', borderColor: '#8A6D3B', borderWidth: 2,
      shadowColor: 'rgba(138,109,59,0.3)', texture: 'vintage',
    },
    fonts: { display: 'Cormorant Garamond', body: 'Crimson Text' },
    decorations: { showDateStamp: true, showCaption: false, showBorder: true, showFilmBorder: true, showVignette: true },
    isPremium: false,
  },
  {
    id: 'summer-picnic',
    name: 'Summer Picnic',
    category: 'classic',
    description: 'Sage gingham and sunshine yellow',
    colors: { primary: '#5C7A52', secondary: '#A9C2A0', accent: '#F0B94E', background: '#F7F5E8' },
    stripStyle: {
      borderRadius: 16, padding: 16, gap: 8,
      backgroundColor: '#F7F5E8', borderColor: '#A9C2A0', borderWidth: 2,
      shadowColor: 'rgba(92,122,82,0.2)', texture: 'none',
    },
    fonts: { display: 'Nanum Gothic', body: 'Inter' },
    decorations: { showDateStamp: true, showCaption: true, showBorder: true, showFilmBorder: false, showVignette: false },
    isPremium: false,
  },
  {
    id: 'cherry',
    name: 'Cherry',
    category: 'classic',
    description: 'Deep cherry red on warm cream, a little dramatic',
    colors: { primary: '#9E2B32', secondary: '#C4595A', accent: '#F0B94E', background: '#FBF3EE' },
    stripStyle: {
      borderRadius: 12, padding: 16, gap: 8,
      backgroundColor: '#FBF3EE', borderColor: '#9E2B32', borderWidth: 1,
      shadowColor: 'rgba(158,43,50,0.2)', texture: 'none',
    },
    fonts: { display: 'Playfair Display', body: 'Inter' },
    decorations: { showDateStamp: true, showCaption: true, showBorder: true, showFilmBorder: false, showVignette: false },
    isPremium: false,
  },
  {
    id: 'blue-sky',
    name: 'Blue Sky',
    category: 'minimal',
    description: 'Open, airy, a single cloud-soft blue accent',
    colors: { primary: '#3E6E96', secondary: '#9FC2DE', accent: '#F0B94E', background: '#FFFFFF' },
    stripStyle: {
      borderRadius: 18, padding: 16, gap: 8,
      backgroundColor: '#FFFFFF', borderColor: '#DCEAF5', borderWidth: 1,
      shadowColor: 'rgba(62,110,150,0.15)', texture: 'none',
    },
    fonts: { display: 'Noto Sans KR', body: 'Inter' },
    decorations: { showDateStamp: true, showCaption: false, showBorder: false, showFilmBorder: false, showVignette: false },
    isPremium: false,
  },
  {
    id: 'cream-paper',
    name: 'Cream Paper',
    category: 'minimal',
    description: 'Quiet, warm, and textured like real paper stock',
    colors: { primary: '#4A4152', secondary: '#8A7D6E', accent: '#F0B94E', background: '#FBF6EE' },
    stripStyle: {
      borderRadius: 10, padding: 18, gap: 10,
      backgroundColor: '#FBF6EE', shadowColor: 'rgba(34,29,40,0.1)', texture: 'paper',
    },
    fonts: { display: 'Fraunces', body: 'Inter' },
    decorations: { showDateStamp: true, showCaption: true, showBorder: false, showFilmBorder: false, showVignette: false },
    isPremium: false,
  },
  {
    id: 'holographic',
    name: 'Holographic',
    category: 'premium',
    description: 'Iridescent shimmer, the loudest strip in the gallery',
    colors: { primary: '#6E63A6', secondary: '#E8A6A3', accent: '#F0B94E', background: '#F1EDFB' },
    stripStyle: {
      borderRadius: 24, padding: 16, gap: 8,
      backgroundColor: 'linear-gradient(135deg, #C9BFE8 0%, #F4C7C3 35%, #F0E6C8 65%, #A9C2A0 100%)',
      shadowColor: 'rgba(201,191,232,0.45)', texture: 'none',
    },
    fonts: { display: 'Space Mono', body: 'Inter' },
    decorations: { showDateStamp: true, showCaption: true, showBorder: false, showFilmBorder: false, showVignette: false },
    isPremium: true,
  },
];

export const TEMPLATE_CATEGORIES = [
  { id: 'all', label: 'All', emoji: '✨' },
  { id: 'classic', label: 'Classic', emoji: '📸' },
  { id: 'modern', label: 'Modern', emoji: '🎯' },
  { id: 'vintage', label: 'Vintage', emoji: '🎞️' },
  { id: 'premium', label: 'Premium', emoji: '💎' },
  { id: 'minimal', label: 'Minimal', emoji: '🌿' },
  { id: 'retro', label: 'Retro', emoji: '📼' },
] as const;

export const DEFAULT_TEMPLATE_ID = 'korean-minimal-white';
